### ISSUE TITLE
Create/Find a Logo

### ISSUE THREAD

**Issue by SPMNJ** [CouponFiends/cosc412project#14]
As a customer, I want to see what kind of company/business (logo) it is so that I don't get confused when other browsers are open. 

Confirmation:
The user will not be confused with a blank logo. With a logo, the user will now know our company/business from others.
Find a good logo to be featured on the login page of the website! It can be custom-made or just a random image on the internet.

https://github.com/CouponFiends/cosc412project/blob/df9ed0261de01980a137ea9a2ab7dcf8cea852e0/index.html#L20

**Comment by ananya224** [comment]
Hey, I would like to design a logo !
