### ISSUE TITLE
Add Click Effect to Buttons

### ISSUE THREAD

**Issue by SPMNJ** [CouponFiends/cosc412project#16]
As a customer, I want to know the website is working fine such as, interactive buttons or indications I'm hovering over a button so that I can make sure the website isn't frozen or my device isn't having any issues.

Confirmation:
The user will be able to know if the buttons are working properly by the color change when hovering over a button.

https://github.com/CouponFiends/cosc412project/blob/df9ed0261de01980a137ea9a2ab7dcf8cea852e0/index.html#L32

We will be adding more aesthetically pleasing "Login" and "Quick Reload" buttons. Hovering over either button would change the shade or color of the button. Once either button is clicked we want a loading circle to show that it's receiving the data.

**Comment by oneamanish** [comment]
see my pull req.
